spring.datasource.url: jdbc:mysql://localhost:3306/blog_engine
spring.datasource.username: root
spring.datasource.password: hWN-h2z-aPE-8dQ
spring.jpa.hibernate.ddl-auto: validate
spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.yaml
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false

application.title: how_to_fix
application.subtitle: how_to_fix
application.phone: 88005553535
application.email: email@mail.ru
application.copyright: Viktor
application.copyrightFrom: 2023
